title = "Sample OAD Process"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = []

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of OpenMDAO model
[model]
    nonlinear_solver = "om.NonlinearBlockGS(iprint=1, maxiter=100)"
    linear_solver = "om.DirectSolver()"
    [model.geometry]
        id = "fastoad.geometry.legacy"
    [model.weights]
        id = "fastoad.weights.legacy"
    [model.aerodynamics]
        id = "fastoad.aerodynamics.highspeed.legacy"
    [model.performance]
        id = "fastoad.performances.breguet.from_owe"
    [model.propulsion]
        id = "fastoad.propulsion.rubber_engine"
