title = "Sample OAD Process"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = []

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver()"

# Definition of OpenMDAO model
[model]
    # Solvers are defined assuming the OpenMDAO convention "import openmdao.api as om"
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=100, reraise_child_analysiserror=False)"
    linear_solver = "om.DirectSolver()"

    # AlThough "model" is a mandatory name for the top level of the model, its sub-components can be freely named by user
    [model.geometry]
        # An OpenMDAO component is identified by its "id"
        id = "fastoad.geometry.legacy"
    [model.weight]
        id = "fastoad.weight.legacy"
    [model.aerodynamics.highspeed]
        id = "fastoad.aerodynamics.highspeed.legacy"
#    [model.aerodynamics.lowspeed]
#        id = "fastoad.aerodynamics.lowspeed.legacy"
    [model.aerodynamics.landing]
        id = "fastoad.aerodynamics.landing.legacy"
        use_xfoil = false
    [model.performance]
        id = "fastoad.performances.breguet"
    [model.propulsion]
        id = "fastoad.propulsion.rubber_engine"
    [model.loop]
        id = "fastoad.loop.wing_area"

[[design_var]]
    name = "data:propulsion:MTO_thrust"
    lower = 0
    ref = 1.5e5
    ref0 = 50000

[[objective]]
    name = "data:weight:aircraft:MTOW"
    ref = 90000
    ref0 = 60000

[[constraint]]
    name = "data:propulsion:thrust_rate"
    lower = 0
    upper = 1
