name: Unit tests

on: [push]

jobs:

  build:

    env:
      PIPENV_VENV_IN_PROJECT: 1

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Pipenv venv cache
        uses: actions/cache@v1
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-${{ matrix.python-version }}-pipenv_venv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.python-version }}-pipenv_venv-

      - name: Create environment and install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: pipenv sync --dev

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .venv
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .venv

      - name: Unit tests
        run: pipenv run pytest tests/unit_tests

